const frontendErrorMessage = {
  'order-03': 'Los campos de la orden no pueden estar vacíos.',
  'app-03': 'Los campos no pueden estar vacíos.',
  'order-18': 'El campo del modulo de orden solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'app-18': 'El campo solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'order-19': 'El campo de orden solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'app-19': 'El campo solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'order-20': 'El campo de orden excede la longitud máxima permitida, por favor reingrese.',
  'app-20': 'El campo excede la longitud máxima permitida, por favor reingrese.',
  'order-21': 'El campo de orden debe ser un numero entero positivo o cero, por favor reingrese.',
  'app-21': 'El campo debe ser un numero entero positivo o cero, por favor reingrese.',
  'order-22':'El campo de orden debe ser un numero entero positivo, por favor reingrese.',
  'app-22':'El campo debe ser un numero entero positivo, por favor reingrese.',
  'order-23': 'El campo de orden debe ser un numero decimal positivo, por favor reingrese.',
  'app-23': 'El campo debe ser un numero decimal positivo, por favor reingrese.',
  'order-24': 'El Guid ingresado en el campo de orden no es válido, por favor reingrese.',
  'app-24': 'El Guid ingresado en el campo no es válido, por favor reingrese.',
  'order-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'app-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'order-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'app-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'order-27': 'No se encontraron ordenes para el cliente especificado.',
  'order-28': 'No se encontraron ordenes con el estado especificado.',
  'order-09': 'No se encontraron ordenes.',
  'app-09': 'No se encontraron resultados.',
  'order-29':'No se encontro la orden que busca.',
  'order-30':'La orden ya se encontraba en el estado especificado.',
  'order-06':'El estado especificado para la orden no es válido.',
  'order-31': 'La orden ha sido cancelada.',
  'order-32':'No se encontro el cliente asociado a la orden.',
  'order-99': 'No se puede completar la orden debido a un error de stock.',
  'app-99': 'No se tiene suficiente stock para completar la operacion.',
  'order-00': 'Ha ocurrido un error inesperado en el sistema de órdenes.',
  'app-00': 'Ha ocurrido un error inesperado en el sistema.',
  'order-01': 'La orden solicitada no existe.',
  'app-01': 'La entidad solicitada no existe.',
  'order-02': 'El campo de orden está fuera de los límites permitidos.',
  'app-02': 'El campo está fuera de los límites permitidos.',
  'order-04': 'El formato del campo de orden es inválido.',
  'app-04': 'El formato del campo es inválido.',
  'order-05':'El campo de orden ya existe en el sistema.',
  'app-05':'El campo ya existe en el sistema.',
  'order-06':'El estado especificado para la orden no es válido.',
  'app-06':'El estado especificado no es válido.',
  'order-08': 'No se encontro la orden.',
  'app-08': 'No se encontro el resultado.',
  'order-10':'Operación no permitida para la orden.',
  'app-10':'Operación no permitida.',
  'order-11': 'Ocurrio un error de aplicacion en el sistema de ordenes.',
  'app-11': 'Ocurrio un error de aplicacion en el sistema.',
};

export {
  frontendErrorMessage,
};