const frontendErrorMessage = {
  'auth-12': 'Rol de usuario inválido.',
  'auth-13': 'La direccion de mail ingresada no es valida.',
  'auth-14': 'El nombre de usuario es demasiado corto, debe tener al menos 6 caracteres',
  'auth-15': 'Este email ya fue utilizado para otra cuenta, por favor elige otro.',
  'auth-16': 'La contraseña debe contener al menos una letra mayúscula, una minúscula, un número y un simbolo. Por favor reingrese',
  'auth-17': 'Este nombre de usuario ya está en uso. Por favor elige otro.',
  'auth-07': 'Nombre de usuario o contraseña incorrectos.',
  'auth-03': 'Los campos de autenticación no pueden estar vacíos.',
  'app-03': 'Los campos no pueden estar vacíos.',
  'auth-18': 'El campo del modulo de autenticacion solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'app-18': 'El campo solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'auth-19': 'El campo de autenticacion solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'app-19': 'El campo solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'auth-20': 'El campo de autenticacion excede la longitud máxima permitida, por favor reingrese.',
  'app-20': 'El campo excede la longitud máxima permitida, por favor reingrese.',
  'auth-21': 'El campo de autenticacion debe ser un numero entero positivo o cero, por favor reingrese.',
  'app-21': 'El campo debe ser un numero entero positivo o cero, por favor reingrese.',
  'auth-22':'El campo de autenticacion debe ser un numero entero positivo, por favor reingrese.',
  'app-22':'El campo debe ser un numero entero positivo, por favor reingrese.',
  'auth-23': 'El campo de autenticacion debe ser un numero decimal positivo, por favor reingrese.',
  'app-23': 'El campo debe ser un numero decimal positivo, por favor reingrese.',
  'auth-24': 'El Guid ingresado en el campo de autenticacion no es válido, por favor reingrese.',
  'app-24': 'El Guid ingresado en el campo no es válido, por favor reingrese.',
  'auth-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'app-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'auth-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'app-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'app-09': 'No se encontraron resultados.',
  'app-99': 'No se tiene suficiente stock para completar la operacion.',
  'auth-00': 'Ha ocurrido un error inesperado en el sistema de autenticación.',
  'app-00': 'Ha ocurrido un error inesperado en el sistema.',
  'auth-01': 'El usuario solicitado no existe.',
  'app-01': 'La entidad solicitada no existe.',
  'auth-02': 'El campo de autenticación está fuera de los límites permitidos.',
  'app-02': 'El campo está fuera de los límites permitidos.',
  'auth-04': 'El formato del campo de autenticación es inválido.',
  'app-04': 'El formato del campo es inválido.',
  'auth-05':'El campo de autenticación ya existe en el sistema.',
  'app-05':'El campo ya existe en el sistema.',
  'auth-06':'El estado especificado para el usuario no es válido.',
  'app-06':'El estado especificado no es válido.',
  'auth-08': 'No se encontro el usuario.',
  'app-08': 'No se encontro el resultado.',
  'auth-10':'Operación no permitida para el usuario.',
  'app-10':'Operación no permitida.',
  'auth-11': 'Ocurrio un error de aplicacion en el sistema de autenticacion.',
  'app-11': 'Ocurrio un error de aplicacion en el sistema.',
};

export {
  frontendErrorMessage,
};