const frontendErrorMessage = {
  'product-03': 'Los campos del producto no pueden estar vacíos.',
  'product-18': 'El campo del modulo de producto solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'product-19': 'El campo de producto solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'product-20': 'El campo de producto excede la longitud máxima permitida, por favor reingrese.',
  'product-21': 'El campo de producto debe ser un numero entero positivo o cero, por favor reingrese.',
  'product-22':'El campo de producto debe ser un numero entero positivo, por favor reingrese.',
  'product-23': 'El campo de producto debe ser un numero decimal positivo, por favor reingrese.',
  'product-24': 'El Guid ingresado en el campo de producto no es válido, por favor reingrese.',
  'product-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'product-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'product-09': 'No se encontraron productos.',
  'product-33': 'El SKU ingresado no es valido, debe ingresar 4 digitos numericos',
  'product-34': 'El codigo interno ingresado no es valido, debe ingresar 4 digitos numericos',
  'product-35': 'El precio para el producto debe ser un decimal mayor a 0',
  'product-36': 'Ya existe un producto con el SKU ingresado, por favor ingrese otro',
  'product-37': 'Ya existe un producto con el codigo interno ingresado, por favor ingrese otro',
  'product-38': 'El producto solicitado se encuentra deshabilitado.',
  'product-99': 'No se tiene suficiente stock para completar la operacion.',
  'product-00': 'Ha ocurrido un error inesperado en el sistema de productos.',
  'product-01': 'El producto solicitado no existe.',
  'product-02': 'El campo de producto está fuera de los límites permitidos.',
  'product-04': 'El formato del campo de producto es inválido.',
  'product-05':'El campo de producto ya existe en el sistema.',
  'product-06':'El estado especificado para el producto no es válido.',
  'product-08': 'No se encontro productos.',
  'product-10':'Operación no permitida para el producto.',
  'product-11': 'Ocurrio un error de aplicacion en el sistema de productos.',
  'app-03': 'Los campos no pueden estar vacíos.',
  'app-18': 'El campo solo debe estar compuesto por letras y numeros, por favor reingrese.',
  'app-19': 'El campo solo debe estar compuesto por letras, simbolos y numeros, por favor reingrese.',
  'app-20': 'El campo excede la longitud máxima permitida, por favor reingrese.',
  'app-21': 'El campo debe ser un numero entero positivo o cero, por favor reingrese.',
  'app-22':'El campo debe ser un numero entero positivo, por favor reingrese.',
  'app-23': 'El campo debe ser un numero decimal positivo, por favor reingrese.',
  'app-24': 'El Guid ingresado en el campo no es válido, por favor reingrese.',
  'app-25': 'El numero de pagina debe ser menor a 1000, por favor reingrese.',
  'app-26': 'La cantidad de elementos por pagina debe ser menor a 15, por favor reingrese.',
  'app-09': 'No se encontraron resultados.',
  'app-99': 'No se tiene suficiente stock para completar la operacion.',
  'app-00': 'Ha ocurrido un error inesperado en el sistema.',
  'app-01': 'La entidad solicitada no existe.',
  'app-02': 'El campo está fuera de los límites permitidos.',
  'app-04': 'El formato del campo es inválido.',
  'app-05':'El campo ya existe en el sistema.',
  'app-06':'El estado especificado no es válido.',
  'app-08': 'No se encontro el resultado.',
  'app-10':'Operación no permitida.',
  'app-11': 'Ocurrio un error de aplicacion en el sistema.',
};

export {
  frontendErrorMessage,
};